include: package:flutter_lints/flutter.yaml
linter:
  rules:
   # Prefer seeing Local Variable types on both sides of declaration
    omit_local_variable_types: false

    # ------ Enable individual rules ------ #
    #                 ---                   #
    # These rules here are good but too     #
    # opinionated to enable them by default #
    # ------------------------------------- #

    # Make constructors the first thing in every class
    sort_constructors_first: true

    # The new tabs vs. spaces. Choose wisely
    prefer_single_quotes: true
    
    # Blindly follow the Flutter code style, which prefers types everywhere
    always_specify_types: true
