name: electrometer
description: A companion app to be used with my LoRA-WAN Electro meter project.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  bloc: ^8.0.1
  cloud_firestore: ^3.1.0
  equatable: ^2.0.3
  firebase_core: ^1.10.0
  fl_chart: ^0.40.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.0
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
  json_annotation: ^4.3.0
  json_serializable: ^6.0.1
  shared_preferences: ^2.0.9

dev_dependencies:
  bloc_test: ^9.0.1
  build_runner: ^2.1.5
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4
  mocktail: ^0.2.0

flutter:
  uses-material-design: true
  generate: true
